name: paper_toast_issue
description: A sample Polymer application
dependencies:
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer:
    entry_points: web/paper_toast_issue.html
